### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by flyke** [Rias500/laravel-mix-critical#2]
Hi,
this successfully generates minified critical css files.

What is the correct way to include them ?
My normal app.css is loaded via an index.blade.php file.
What should I do so that a vue route, like /app#/dashboard loads my generated dashboard.critical.css ?

**Comment by riasvdv** [comment]
You'll have to find a way to inline the contents of the file into your layout.

This should help you get a step further: https://stackoverflow.com/questions/30316548/how-to-embed-css-to-html-in-laravel
